### ISSUE TITLE
The nova compute service doesn't start after applying the patch

### ISSUE THREAD

**Issue by jorgefg** [codedellemc/nova-scaleio-ephemeral#1]
Hi folks,
I've sucessfully applied the Nova patch in a Mitaka deployment (13.1.2). After configuring Nova to use sio ephemeral disks, compute service failed to start:

```
CRITICAL nova [-] AttributeError: 'module' object has no attribute 'SIOGROUP'
ERROR nova Traceback (most recent call last):
ERROR nova   File "/usr/bin/nova-compute", line 10, in <module>
ERROR nova     sys.exit(main())
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/cmd/compute.py", line 74, in main
ERROR nova     db_allowed=CONF.conductor.use_local)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/service.py", line 290, in create
ERROR nova     db_allowed=db_allowed)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/service.py", line 173, in __init__
ERROR nova     self.manager = manager_class(host=self.host, *args, **kwargs)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 727, in __init__
ERROR nova     self.driver = driver.load_compute_driver(self.virtapi, compute_driver)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/driver.py", line 1623, in load_compute_driver
ERROR nova     virtapi)
ERROR nova   File "/usr/lib/python2.7/site-packages/oslo_utils/importutils.py", line 62, in import_object_ns
ERROR nova     cls = import_class(import_value)
ERROR nova   File "/usr/lib/python2.7/site-packages/oslo_utils/importutils.py", line 30, in import_class
ERROR nova     __import__(mod_str)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/__init__.py", line 15, in <module>
ERROR nova     from nova.virt.libvirt import driver
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py", line 102, in <module>
ERROR nova     from nova.virt.libvirt import imagebackend
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/imagebackend.py", line 47, in <module>
ERROR nova     from nova.virt.libvirt.storage import sio_utils
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/storage/sio_utils.py", line 36, in <module>
ERROR nova     CONF.register_group(siolib.SIOGROUP)
ERROR nova AttributeError: 'module' object has no attribute 'SIOGROUP'
ERROR nova
```

The python-scaleioclient is already installed.

Any suggestion would be appreciated.

Thank you!!
Jorge.

**Comment by Andrey-mp** [comment]
Hi, What version of siolib installed in your system?It should be https://github.com/codedellemc/python-scaleioclient/tree/mitaka for mitaka.(or https://github.com/codedellemc/puppet-scaleio-openstack/blob/master/files/mitaka/siolib-1.5.5.tar.gz ) Regards,Andrey. 17.11.2016, 13:33, "jorgefg" notifications@github.com:Hi folks,I've sucessfully applied the Nova patch in a Mitaka deployment (13.1.2). After configuring Nova to use sio ephemeral disks, compute service failed to start:CRITICAL nova [-] AttributeError: 'module' object has no attribute 'SIOGROUP'
ERROR nova Traceback (most recent call last):
ERROR nova   File "/usr/bin/nova-compute", line 10, in <module>
ERROR nova     sys.exit(main())
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/cmd/compute.py", line 74, in main
ERROR nova     db_allowed=CONF.conductor.use_local)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/service.py", line 290, in create
ERROR nova     db_allowed=db_allowed)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/service.py", line 173, in **init**
ERROR nova     self.manager = manager_class(host=self.host, _args, *_kwargs)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/compute/manager.py", line 727, in **init**
ERROR nova     self.driver = driver.load_compute_driver(self.virtapi, compute_driver)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/driver.py", line 1623, in load_compute_driver
ERROR nova     virtapi)
ERROR nova   File "/usr/lib/python2.7/site-packages/oslo_utils/importutils.py", line 62, in import_object_ns
ERROR nova     cls = import_class(import_value)
ERROR nova   File "/usr/lib/python2.7/site-packages/oslo_utils/importutils.py", line 30, in import_class
ERROR nova     **import**(mod_str)
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/**init**.py", line 15, in <module>
ERROR nova     from nova.virt.libvirt import driver
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/driver.py", line 102, in <module>
ERROR nova     from nova.virt.libvirt import imagebackend
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/imagebackend.py", line 47, in <module>
ERROR nova     from nova.virt.libvirt.storage import sio_utils
ERROR nova   File "/usr/lib/python2.7/site-packages/nova/virt/libvirt/storage/sio_utils.py", line 36, in <module>
ERROR nova     CONF.register_group(siolib.SIOGROUP)
ERROR nova AttributeError: 'module' object has no attribute 'SIOGROUP'
ERROR nova
The python-scaleioclient is already installed.Any suggestion would be appreciated.Thank you!!Jorge.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jorgefg** [comment]
I've installed the most recent version 2.0.0.dev2. I'll try with the right version 1.5.5 and let's see.

Thank you!
Jorge.

**Comment by jorgefg** [comment]
Now its working fine. Congratulations for your great job!

Thanks!
Jorge.
